sudo: required
services:
    - docker

before_install:
    - docker build -t yuliyalmaty/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true yuliyalmaty/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-847220784019"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY